name: 💡 Feature Request
description: Suggest a new feature or enhancement for MyDebugTools
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please fill out the form below to help us understand your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe what you're trying to accomplish.
      placeholder: "Example: I'm always frustrated when I need to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution or feature you'd like to see implemented.
      placeholder: "Example: I would like to have a tool that..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "Example: I've tried using X but it doesn't..."
    validations:
      required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Tool
        - Enhancement to Existing Tool
        - UI/UX Improvement
        - Performance Improvement
        - Integration with External Service
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Just a suggestion
    validations:
      required: false

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What are the main benefits of implementing this feature?
      placeholder: |
        - Improves productivity by...
        - Saves time when...
        - Makes it easier to...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, mockups, or examples about the feature request here.
      placeholder: You can attach images by dragging & dropping, selecting them, or pasting from the clipboard.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this feature request, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
