'use client';

import { CurlyBracesIcon, Terminal, Github, Bug } from 'lucide-react';
import { useState } from 'react';

// Tools ordered by popularity and trending status
const tools = [
  {
    name: 'JSON Formatter',
    description: 'Format and validate JSON data with syntax highlighting',
    icon: CurlyBracesIcon,
    href: '/tools/json',
    color: 'text-blue-500',
    bgColor: 'bg-blue-50',
    hoverColor: 'hover:bg-blue-100',
    isNew: false,
    isTrending: true,
  },
  {
    name: 'JWT Decoder',
    description: 'Decode and verify JSON Web Tokens',
    icon: Terminal,
    href: '/tools/jwt',
    color: 'text-green-500',
    bgColor: 'bg-green-50',
    hoverColor: 'hover:bg-green-100',
    isNew: false,
    isTrending: true,
  },
  {
    name: 'Base64 Tools',
    description: 'Encode and decode Base64 strings',
    icon: Terminal,
    href: '/tools/base64',
    color: 'text-purple-500',
    bgColor: 'bg-purple-50',
    hoverColor: 'hover:bg-purple-100',
    isNew: false,
    isTrending: false,
  },
  {
    name: 'API Tester',
    description: 'Test and debug API endpoints',
    icon: Terminal,
    href: '/tools/api',
    color: 'text-yellow-500',
    bgColor: 'bg-yellow-50',
    hoverColor: 'hover:bg-yellow-100',
    isNew: false,
    isTrending: true,
  },
  {
    name: 'Regex Tester',
    description: 'Test and debug regular expressions',
    icon: Terminal,
    href: '/tools/regex',
    color: 'text-red-500',
    bgColor: 'bg-red-50',
    hoverColor: 'hover:bg-red-100',
    isNew: false,
    isTrending: false,
  },
  {
    name: 'Icon Finder',
    description: 'Search and browse icons from popular icon sets',
    icon: Terminal,
    href: '/tools/icons',
    color: 'text-indigo-500',
    bgColor: 'bg-indigo-50',
    hoverColor: 'hover:bg-indigo-100',
    isNew: false,
    isTrending: false,
  },
  {
    name: 'Color Picker',
    description: 'Pick and convert colors in different formats',
    icon: Terminal,
    href: '/tools/color',
    color: 'text-pink-500',
    bgColor: 'bg-pink-50',
    hoverColor: 'hover:bg-pink-100',
    isNew: false,
    isTrending: false,
  },
  {
    name: 'CSS Tools',
    description: 'Format and minify CSS code',
    icon: Terminal,
    href: '/tools/css',
    color: 'text-orange-500',
    bgColor: 'bg-orange-50',
    hoverColor: 'hover:bg-orange-100',
    isNew: false,
    isTrending: false,
  },
  {
    name: 'Markdown Editor',
    description: 'Edit and preview Markdown content',
    icon: Terminal,
    href: '/tools/markdown',
    color: 'text-teal-500',
    bgColor: 'bg-teal-50',
    hoverColor: 'hover:bg-teal-100',
    isNew: false,
    isTrending: false,
  },
  {
    name: 'Code Diff',
    description: 'Compare and merge code changes',
    icon: Terminal,
    href: '/tools/code-diff',
    color: 'text-cyan-500',
    bgColor: 'bg-cyan-50',
    hoverColor: 'hover:bg-cyan-100',
    isNew: false,
    isTrending: false,
  },
  {
    name: 'Database Query Tool',
    description: 'Query and manage SQLite databases',
    icon: Terminal,
    href: '/tools/database',
    color: 'text-emerald-500',
    bgColor: 'bg-emerald-50',
    hoverColor: 'hover:bg-emerald-100',
    isNew: false,
    isTrending: false,
  },
  {
    name: 'HTML Tools',
    description: 'Format and validate HTML code',
    icon: Terminal,
    href: '/tools/html',
    color: 'text-violet-500',
    bgColor: 'bg-violet-50',
    hoverColor: 'hover:bg-violet-100',
    isNew: false,
    isTrending: false,
  },
  {
    name: 'HTTP Status Codes',
    description: 'Reference guide for HTTP status codes',
    icon: Terminal,
    href: '/tools/http-status',
    color: 'text-rose-500',
    bgColor: 'bg-rose-50',
    hoverColor: 'hover:bg-rose-100',
    isNew: true,
    isTrending: true,
  },
];

export default function ToolsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
} 