export const answerPages = [
  {
    slug: 'best-free-json-formatter',
    title: 'What is the best free JSON formatter for developers?',
    description: 'Use a browser-based JSON formatter that can format, validate, repair, and inspect payloads without requiring an account.',
    shortAnswer: 'The best free JSON formatter validates syntax, formats nested payloads clearly, and keeps sensitive JSON local to your browser when possible.',
    toolHref: '/tools/json/',
    toolName: 'JSON Formatter',
    steps: [
      'Paste the JSON payload into the formatter.',
      'Run validation before trusting the output.',
      'Use formatted output to inspect nesting, arrays, and object keys.',
      'Repair malformed JSON only after reviewing the suggested changes.',
    ],
    related: ['JWT Decoder', 'API Workbench', 'Base64 Encoder and Decoder'],
  },
  {
    slug: 'how-to-decode-jwt-safely',
    title: 'How do I decode a JWT safely?',
    description: 'Decode JWT headers and payloads locally, inspect claims, and avoid pasting production secrets into tools you do not trust.',
    shortAnswer: 'Decode JWTs in a local browser tool, review claims such as exp, iss, aud, and sub, and verify signatures separately when authenticity matters.',
    toolHref: '/tools/jwt/',
    toolName: 'JWT Decoder',
    steps: [
      'Paste the token into a trusted JWT decoder.',
      'Review the header algorithm and token type.',
      'Inspect payload claims such as expiration, issuer, audience, and subject.',
      'Do not treat decoded claims as verified unless the signature is validated.',
    ],
    related: ['JSON Formatter', 'Base64 Encoder and Decoder', 'API Workbench'],
  },
  {
    slug: 'base64-encode-vs-decode',
    title: 'What is the difference between Base64 encoding and decoding?',
    description: 'Understand when to encode data into Base64, when to decode it, and how to inspect encoded strings during debugging.',
    shortAnswer: 'Base64 encoding converts bytes or text into an ASCII-safe representation. Decoding converts that Base64 text back into the original bytes or string.',
    toolHref: '/tools/base64/',
    toolName: 'Base64 Encoder and Decoder',
    steps: [
      'Encode when data must travel through text-only systems.',
      'Decode when you need to inspect the original content.',
      'Check whether the input is plain text, binary, image, or a data URL.',
      'Avoid confusing Base64 with encryption; it is reversible encoding.',
    ],
    related: ['JWT Decoder', 'JSON Formatter', 'API Workbench'],
  },
  {
    slug: 'test-api-request-online',
    title: 'How can I test an API request online?',
    description: 'Send HTTP requests, set headers and auth, inspect responses, and organize API calls in a browser-based tester.',
    shortAnswer: 'Use an API tester to choose the method, enter the URL, add headers or auth, send the request, and inspect status, response headers, and body.',
    toolHref: '/tools/api/',
    toolName: 'API Workbench',
    steps: [
      'Choose the HTTP method such as GET, POST, PUT, PATCH, or DELETE.',
      'Enter the endpoint URL and any query parameters.',
      'Add required headers, authentication, and request body.',
      'Send the request and review status code, headers, timing, and response body.',
    ],
    related: ['HTTP Status Codes', 'JSON Formatter', 'JWT Decoder'],
  },
  {
    slug: 'compare-two-code-snippets',
    title: 'How do I compare two code snippets?',
    description: 'Use a code diff tool to compare snippets, review changed lines, and debug configuration or release differences.',
    shortAnswer: 'Paste the old snippet and new snippet into a diff tool, then review added, removed, and changed lines side by side.',
    toolHref: '/tools/code-diff/',
    toolName: 'Code Diff Tool',
    steps: [
      'Paste the original code into the left side.',
      'Paste the changed code into the right side.',
      'Review highlighted additions, removals, and modified lines.',
      'Use the result to guide code review, debugging, or release notes.',
    ],
    related: ['Build Diff', 'Bundle Analyzer', 'Crash Beautifier'],
  },
  {
    slug: 'generate-hash-for-text',
    title: 'How do I generate a hash for text?',
    description: 'Generate SHA hashes for text or payloads in the browser and use them as checksums during debugging.',
    shortAnswer: 'Paste text into a hash generator, choose the algorithm you need, and compare the generated digest with the expected checksum.',
    toolHref: '/tools/hash/',
    toolName: 'Hash Generator',
    steps: [
      'Paste the text, payload, or checksum source into the hash tool.',
      'Choose the required algorithm, such as SHA-256.',
      'Copy the generated digest exactly as shown.',
      'Use hashes for comparison and integrity checks, not for reversible encoding.',
    ],
    related: ['Base64 Encoder and Decoder', 'JSON Formatter', 'JWT Decoder'],
  },
  {
    slug: 'decode-url-query-string',
    title: 'How do I decode a URL query string?',
    description: 'Decode URLs and query strings locally to inspect escaped characters, parameters, and redirect targets.',
    shortAnswer: 'Use a URL decoder to convert percent-encoded characters back to readable text, then inspect each query parameter separately.',
    toolHref: '/tools/url/',
    toolName: 'URL Encoder and Decoder',
    steps: [
      'Paste the full URL or encoded component into the URL tool.',
      'Decode percent-encoded characters into readable text.',
      'Inspect query parameter names, values, and repeated keys.',
      'Be careful with redirect URLs and tokens before sharing decoded output.',
    ],
    related: ['API Workbench', 'HTTP Status Codes', 'JSON Formatter'],
  },
  {
    slug: 'what-http-status-code-means',
    title: 'How do I check what an HTTP status code means?',
    description: 'Look up HTTP status codes by number or category and connect the result to API debugging context.',
    shortAnswer: 'Search the status code, confirm its category, then use the meaning to decide whether the issue is client-side, server-side, redirect-related, or informational.',
    toolHref: '/tools/http-status/',
    toolName: 'HTTP Status Codes',
    steps: [
      'Enter the status code or browse by category.',
      'Read the concise meaning and standard status family.',
      'Compare the result with the request method, headers, and response body.',
      'Use API logs or an API tester when the code alone is not enough context.',
    ],
    related: ['API Workbench', 'URL Encoder and Decoder', 'JSON Formatter'],
  },
  {
    slug: 'use-ai-debug-assistant-safely',
    title: 'How should I use an AI debug assistant safely?',
    description: 'Use AI-assisted debugging for errors and logs while avoiding secrets, production credentials, and private customer data.',
    shortAnswer: 'Use an AI debug assistant for non-sensitive errors, stack traces, API responses, and JSON issues, but remove secrets and private data before sending text to any configured AI provider.',
    toolHref: '/tools/ai/',
    toolName: 'AI Debug Assistant',
    steps: [
      'Paste only the smallest error, response, log, or stack trace needed to explain the issue.',
      'Remove API keys, cookies, tokens, customer data, internal URLs, and production credentials.',
      'Include the runtime, framework, endpoint method, or expected behavior when it helps the analysis.',
      'Treat the response as debugging guidance and verify any suggested code or configuration change locally.',
    ],
    related: ['API Workbench', 'JSON Formatter', 'HTTP Status Codes'],
  },
  {
    slug: 'explain-stack-trace',
    title: 'How do I explain a stack trace?',
    description: 'Find the exception type, first app-owned frame, dependency frames, and likely root cause from a pasted stack trace.',
    shortAnswer: 'Start with the exception message, then find the first frame owned by your application. That frame usually points to the code path to inspect first.',
    toolHref: '/tools/stack-trace/',
    toolName: 'Stack Trace Explainer',
    steps: [
      'Paste the full stack trace, including the exception message.',
      'Identify the exception type and message before reading every frame.',
      'Find the first app-owned frame below framework or dependency frames.',
      'Use the surrounding request, input, or deploy change to confirm the likely cause.',
    ],
    related: ['Crash Beautifier', 'Log Trace Rebuilder', 'AI Debug Assistant'],
  },
  {
    slug: 'rebuild-log-trace',
    title: 'How do I rebuild a trace from logs?',
    description: 'Group logs by request ID, trace ID, correlation ID, timestamp, service, severity, and repeated error signatures.',
    shortAnswer: 'Collect logs around one failing request, group by request or trace ID, then order the events by timestamp to find the first error and downstream failures.',
    toolHref: '/tools/log-trace/',
    toolName: 'Log Trace Rebuilder',
    steps: [
      'Paste the logs that surround one failing request or incident window.',
      'Group lines by trace ID, request ID, correlation ID, or service name.',
      'Sort the events by timestamp and mark the first error or warning.',
      'Separate the initiating failure from retries, timeouts, and downstream symptoms.',
    ],
    related: ['Stack Trace Explainer', 'OpenTelemetry Trace Viewer', 'Error Tracker'],
  },
  {
    slug: 'analyze-har-file',
    title: 'How do I analyze a HAR file?',
    description: 'Inspect browser HAR exports for slow requests, redirects, failed responses, duplicate calls, payload size, and cache behavior.',
    shortAnswer: 'Load the HAR, sort by failed or slow requests, then inspect status, timing, redirects, payload size, and cache headers for the first broken dependency.',
    toolHref: '/tools/http-profiler/',
    toolName: 'HAR Analyzer / HTTP Profiler',
    steps: [
      'Export the HAR from the browser Network tab without sharing sensitive cookies.',
      'Inspect failed requests, long waits, redirects, and unusually large payloads.',
      'Compare request headers, response headers, status, and timing phases.',
      'Turn the first meaningful failure into a minimal API request or browser reproduction.',
    ],
    related: ['API Workbench', 'HTTP Status Codes', 'Redirect Inspector'],
  },
  {
    slug: 'debug-github-actions-failure',
    title: 'How do I debug a GitHub Actions failure?',
    description: 'Read CI logs and workflow YAML to find the failed step, risky shell command, dependency issue, or missing environment value.',
    shortAnswer: 'Find the first failed step in the job, read a few lines above the error, then check whether the workflow command, dependency cache, secret, or environment changed.',
    toolHref: '/tools/ci-debugger/',
    toolName: 'CI / GitHub Actions Debugger',
    steps: [
      'Paste the failed job log and the relevant workflow YAML.',
      'Find the first failed command instead of the final summary line.',
      'Check cache, dependency install, environment variables, permissions, and matrix values.',
      'Reproduce locally with the same command before changing the pipeline.',
    ],
    related: ['Build Diff', 'Bundle Analyzer', 'Secret Scanner'],
  },
  {
    slug: 'debug-cors-security-headers',
    title: 'How do I debug CORS and security headers?',
    description: 'Inspect response headers for CORS mistakes, CSP violations, cookie flags, cache-control, and missing browser protections.',
    shortAnswer: 'Capture the exact response headers for the failing request, then check origin, credentials, allowed methods, CSP, cookie flags, and caching rules together.',
    toolHref: '/tools/security-headers/',
    toolName: 'Security Headers + CORS Inspector',
    steps: [
      'Paste the response headers from the failing browser request.',
      'Check Access-Control-Allow-Origin, credentials, methods, and preflight behavior.',
      'Inspect CSP, HSTS, X-Content-Type-Options, frame protection, and referrer policy.',
      'Review Set-Cookie flags such as Secure, HttpOnly, SameSite, Domain, Path, and expiry.',
    ],
    related: ['CSP Parser', 'Cookie Security Inspector', 'API Workbench'],
  },
  {
    slug: 'debug-kubernetes-crashloopbackoff',
    title: 'How do I debug Kubernetes CrashLoopBackOff?',
    description: 'Use pod status, describe output, events, restart counts, probes, image pulls, and logs to isolate a Kubernetes failure.',
    shortAnswer: 'Start with pod events and the previous container logs. CrashLoopBackOff is usually caused by process exit, failed probes, missing config, image issues, or startup dependency failures.',
    toolHref: '/tools/k8s-debug/',
    toolName: 'Kubernetes Debug Helper',
    steps: [
      'Paste kubectl get pods, describe pod, events, and previous container logs.',
      'Check restart count, exit code, last state, image pull status, and probe failures.',
      'Verify ConfigMaps, Secrets, service accounts, resource limits, and startup dependencies.',
      'Run the smallest kubectl command that confirms the suspected failure mode.',
    ],
    related: ['Log Trace Rebuilder', 'Secret Scanner', 'OpenTelemetry Trace Viewer'],
  },
  {
    slug: 'inspect-opentelemetry-trace',
    title: 'How do I inspect an OpenTelemetry trace?',
    description: 'Analyze spans, root operations, slow child spans, error attributes, service paths, and incident timing from local trace data.',
    shortAnswer: 'Find the root span, then inspect slow spans and spans with error status. The first upstream error span often explains the rest of the trace.',
    toolHref: '/tools/otel-trace-viewer/',
    toolName: 'OpenTelemetry Trace Viewer',
    steps: [
      'Paste OTLP JSON, exported spans, or a trace summary.',
      'Find the root span, service path, total duration, and error spans.',
      'Sort child spans by duration and look for retries, database calls, and network waits.',
      'Compare span attributes with logs or API responses from the same request ID.',
    ],
    related: ['Log Trace Rebuilder', 'HTTP Traffic Inspector', 'Kubernetes Debug Helper'],
  },
  {
    slug: 'debug-oauth-redirect-uri-mismatch',
    title: 'How do I fix redirect_uri_mismatch in OAuth?',
    description: 'Compare OAuth callback URLs, domains, schemes, trailing slashes, client IDs, and provider configuration.',
    shortAnswer: 'Use the exact redirect_uri sent in the OAuth request and add that same scheme, host, path, and trailing slash to the provider client configuration.',
    toolHref: '/tools/saml-oidc-debugger/',
    toolName: 'SAML / OIDC Debugger',
    steps: [
      'Copy the redirect_uri value from the generated authorize URL.',
      'Compare scheme, domain, path, query, and trailing slash with the provider console.',
      'Confirm the app is using the intended client ID and environment.',
      'Retry sign-in only after the provider has saved the updated callback URL.',
    ],
    related: ['OAuth Token Inspector', 'API Auth Config Tester', 'URL Encoder and Decoder'],
  },
  {
    slug: 'scan-logs-for-secrets',
    title: 'How do I scan logs for secrets before sharing?',
    description: 'Find likely API keys, tokens, private keys, database URLs, cookies, and credential-looking values before posting logs publicly.',
    shortAnswer: 'Scan the log text for key, token, secret, cookie, private key, and connection-string patterns, then replace values with stable placeholders before sharing.',
    toolHref: '/tools/secret-scanner/',
    toolName: 'Secret Scanner',
    steps: [
      'Paste the smallest log or config snippet needed for review.',
      'Look for API keys, bearer tokens, cookies, private keys, and database URLs.',
      'Replace sensitive values with placeholders that preserve shape but remove the secret.',
      'Rotate any credential that was already shared outside a trusted boundary.',
    ],
    related: ['Security Headers + CORS Inspector', 'JWT Decoder', 'AI Debug Assistant'],
  },
  {
    slug: 'generate-strong-password-locally',
    title: 'How do I generate a strong password locally?',
    description: 'Generate strong passwords in the browser with length, character class, ambiguity, copy, and strength controls.',
    shortAnswer: 'Use a local password generator, choose a long length, include enough character variety, avoid ambiguous characters when humans must type it, and store the result in a password manager.',
    toolHref: '/tools/password-generator/',
    toolName: 'Password Generator',
    steps: [
      'Choose a password length that matches the account policy.',
      'Enable character classes needed by the service.',
      'Disable ambiguous characters if the password must be typed manually.',
      'Copy the generated password directly into a password manager.',
    ],
    related: ['Hash Generator', 'Secret Scanner', 'JWT Decoder'],
  },
] as const

export type AnswerSlug = (typeof answerPages)[number]['slug']

export function getAnswerPage(slug: string) {
  return answerPages.find((page) => page.slug === slug)
}
